[technote]
id = "SQR-081"
series_id = "SQR"
canonical_url = "https://sqr-081.lsst.io/"
github_url = "https://github.com/lsst-sqre/sqr-081"
github_default_branch = "main"
date_created = "2015-11-18"
date_updated = "2023-11-01"

[[technote.authors]]
name = { given_names = "Frossie", family_names = "Economou" }
orcid = "https://orcid.org/0000-0001-2345-6789"
affiliations = [
    { name = "Rubin Observatory", ror = "https://ror.org/048g3cy84" }
]

[[technote.status]]
state = "other"
note = '**This is not a Rubin Data Management policy document;it is an explanation of practice in one team. It is beingpublished for transparency and in the hope of sparking usefuldiscussions.**\n\nThis document, while non-technical, is writtenin a technical context. In particular, the word "bias" is used inits technical sense ("a systematic distortion of a statistical resultdue to a factor not allowed for in its derivation") rather that itscolloquial sense (synonymous w/ prejudice).'
